Fixed user/group checking
Also added consistency in the use of tabs and capitalization for info/warning/debug etc

diff --git a/jackett/jackett.init b/jackett/jackett.init
--- a/jackett/jackett.init
+++ b/jackett/jackett.init
@@ -1,12 +1,12 @@
 #!/bin/bash
 ### BEGIN INIT INFO
-# Provides:          jackett
-# Required-Start:    $remote_fs $syslog
-# Required-Stop:     $remote_fs $syslog
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
+# Provides: jackett
+# Required-Start: $remote_fs $syslog
+# Required-Stop: $remote_fs $syslog
+# Default-Start: 2 3 4 5
+# Default-Stop: 0 1 6
 # Short-Description: Starts Jackett
-# Description:       Start jackett on start. Change USER= before running
+# Description: Start jackett on start. Change USER= before running
 ### END INIT INFO
 
 # Author: Jesper Smith
@@ -59,25 +59,23 @@ do_start()
 	fi
 	
 	# Check for log file. If it doesn't exist, create it.
-	if [ -f $JACKETTLOGPATH$JACKETTLOG ];
-	then
-        	echo "Logging to $JACKETTLOGPATH$JACKETTLOG."
+	if [ -f $JACKETTLOGPATH$JACKETTLOG ]; then
+		echo "Logging to $JACKETTLOGPATH$JACKETTLOG."
 	else
-        	echo "Log file $JACKETTLOGPATH$JACKETTLOG doesn't exist. Creating it..."
-	        touch $JACKETTLOGPATH$JACKETTLOG
-        	if [ -f $JACKETTLOGPATH$JACKETTLOG ];
-                	then
-				chown $USER:$GROUP $JACKETTLOGPATH$JACKETTLOG
-                        	echo "Logfile created. Logging to $JACKETTLOGPATH$JACKETTLOG"
-	                else
-        	                echo "Couldn't create logfile $JACKETTLOGPATH$JACKETTLOG. Please investigate."
-	        fi
+		echo "Log file $JACKETTLOGPATH$JACKETTLOG doesn't exist. Creating it..."
+		touch $JACKETTLOGPATH$JACKETTLOG
+		if [ -f $JACKETTLOGPATH$JACKETTLOG ]; then
+			chown $USER:$GROUP $JACKETTLOGPATH$JACKETTLOG
+			echo "Logfile created. Logging to $JACKETTLOGPATH$JACKETTLOG"
+		else
+			echo "Couldn't create logfile $JACKETTLOGPATH$JACKETTLOG. Please investigate."
+		fi
 	fi
 
-        # Return
-        #   0 if daemon has been started
-        #   1 if daemon was already running
-        #   2 if daemon could not be started
+		# Return
+		# 0 if daemon has been started
+		# 1 if daemon was already running
+		# 2 if daemon could not be started
 
 	start-stop-daemon --start --chuid $USER:$GROUP --test --quiet --make-pidfile --pidfile $PIDFILE --background --exec /bin/bash -- -c "$DAEMONSTRING" || return 1
 
@@ -95,7 +93,6 @@ do_stop()
 	sleep 2
 	return "$?"
 }
-
 
 case "$1" in
   start)
@@ -115,8 +112,8 @@ case "$1" in
 	esac
 	;;
   status)
-       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
-       ;;
+	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	;;
   restart|force-reload)
 	log_daemon_msg "Restarting $DESC" "$NAME"
 	do_stop
@@ -136,7 +133,6 @@ case "$1" in
 	esac
 	;;
   *)
-	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
 	echo "Usage: service jackett {start|stop|status|restart|force-reload}" >&2
 	exit 3
 	;;
